const ROOT_HEADER = document.getElementById('header')
const ROOT_GOODS = document.getElementById('goods')
const ROOT_PRODUCTS = document.getElementById('products')
const ROOT_PRODUCTS_CAT = document.getElementById('products-cat')
const ROOT_SHOPPING = document.getElementById('shopping')
const ROOT_FOOTER = document.getElementById('footer')
