const CATALOG = [
    {
        id: '1',
        img: 
            'img/catalog/CARNIVAL LADY ELITE/carnivalladyvip1a-590x590.jpg',

            
        name: 'CARNIVAL LADY ELITE',
        rating: '',
        review: '',
        price: 79,
        sex: 'male',
        categories: 'man'
    },
    {
        id: '2',
        img: 'img/catalog/CARNIVAL WHITE/carnivalwhite1-300x300.jpg',
        name: 'CARNIVAL WHITE',
        rating: '',
        review: '',
        price: 59,
        sex: 'male',
    },
    {
        id: '3',
        img: 'img/catalog/CURREN GRASS/currengrass1-300x300.jpg',
        name: 'CURREN GRASS',
        rating: '',
        review: '',
        price: 29,
        sex: 'male',
    },
    {
        id: '4',
        img: 'img/catalog/guanquin-liberty-mainnn-300x300.jpg',
        name: 'CURREN MONREAL',
        rating: '',
        review: '',
        price: 139,
        sex: 'male',
    },
    {
        id: 'el5',
        img: 'img/catalog/carnivalwhite1-300x300.jpg',
        name: 'GUANQUIN LIBERTY',
        rating: '',
        review: '',
        price: 99,
        sex: 'male',
    },
    {
        id: 'el6',
        img: 'img/catalog/lobinnibusiness1-300x300.jpg',
        name: 'LOBINNI BUSINESS',
        rating: '',
        review: '',
        price: 199,
        sex: 'male',
    },
    {
        id: 'el7',
        img: 'img/catalog/SKMEI KOMPASS PRO BLACK/skmeikompassproblack1-300x300.jpg',
        name: 'SKMEI KOMPASS PRO BLACK',
        rating: '',
        review: '',
        price: 179,
        sex: 'male',
    },
    {
        id: 'el8',
        img: 'img/catalog/sunktaceramic1-300x300.jpg',
        name: 'SUNKTA CERAMIC',
        rating: '',
        review: '',
        price: 49,
        sex: 'male',
    },
    {
        id: 'el9',
        img: 'img/catalog/winner-black-1-400x400-300x300.jpg',
        name: 'WINNER BLACK',
        rating: '',
        review: '',
        price: 139,
        sex: 'male',
    },
    {
        id: 'el10',
        img: 'img/catalog/smartmiobandpromain-590x590.jpg',
        name: 'SMART MIOBAND PRO GOLD',
        rating: '',
        review: '',
        price: 99,
        sex: 'male',
    },
    {
        id: 'el11',
        img: 'img/catalog/smartkissmain-590x590.jpg',
        name: 'SMART KISS GOLD',
        rating: '',
        review: '',
        price: 196,
        sex: 'male',
    },
    {
        id: 'el12',
        img: 'img/catalog/smartpowernano1-590x590.jpg',
        name: 'SMART POWER NANO BLACK',
        rating: '',
        review: '',
        price: 170,
        sex: 'male',
    },
    {
        id: 'el13',
        img: 'img/catalog/hemsutmilitarymain1-590x590.jpg',
        name: 'Hemsut Military with compass',
        rating: '',
        review: '',
        price: 59,
        sex: 'male',
    },
    
    
]